config:
    liveReloadPort: 35740
    files:
        img:
            src:
              - web/img/**/*.{png,jpg,gif}
              - web/assets/**/*.{png,jpg,gif}
        js:
            app:
                src:
                  - Gruntfile.js
                  - web/js/require-main.js
                  - web/js/app.js
                  - web/js/apps/**/*.js
                  - web/js/components/**/*.js
                  - web/js/data/**/*.js
                  - web/js/entities/**/*.js
                  - web/js/extensions/**/*.js
            livereload: web/js/livereload.js
        handlebars:
            src: web/js/**/*.hbs
        scss:
            loadPaths:
              - web/css
              - web/vendor
              - web/vendor/bootstrap-sass-official/vendor/assets/stylesheets/bootstrap
              - web/vendor/bourbon/dist
              - web/vendor/neat/app/assets/stylesheets
            app:
                src:
                  - web/css/application.scss
                dest: web/css/main.css
        scssImport:
            watch:
                - web/css/**/*.scss
                - '!web/css/*.css'
                - '!web/css/application.scss'
    requirejs:
        appDir: ./web/js
        baseUrl: ./
        dir: ./web/build
        mainConfigFile: ./web/js/require-main.js
        modules:
            - name: require-main
